# Generated by Django 4.2.5 on 2023-09-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_athlete_confirm_password_athlete_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Athlete',
        ),
    ]
