# Generated by Django 4.2.5 on 2023-09-21 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_remove_customuser_confirm_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Athlete",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("profile_picture", models.ImageField(upload_to="profile_pictures/")),
                ("achievements", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Sponsor_ID", models.CharField(max_length=20)),
                ("Organisation", models.CharField(max_length=255)),
                ("Bio", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("athlete", "Athlete"),
                    ("regular_user", "Regular User"),
                    ("sponsor", "sponsor"),
                    ("admin", "Admin"),
                ],
                default="regular_user",
                max_length=15,
                verbose_name="Role",
            ),
        ),
    ]
