# Generated by Django 4.2.5 on 2023-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_athlete_sponsor_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("athlete", "Athlete"),
                    ("regular_user", "RegularUser"),
                    ("sponsor", "Sponsor"),
                    ("admin", "Admin"),
                ],
                default="regular_user",
                max_length=15,
                verbose_name="Role",
            ),
        ),
    ]
