# Generated by Django 4.2.5 on 2023-09-21 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_athlete_sponsor_alter_customuser_role"),
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation",
            options={"verbose_name_plural": "Donations"},
        ),
        migrations.AddField(
            model_name="donation",
            name="athlete",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="user.athlete",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="sponsors",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsored_donations",
                to="user.sponsor",
            ),
        ),
    ]
