# Generated by Django 4.2.5 on 2023-10-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("register", "0001_initial"),
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="athlete",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="register.athlete",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="sponsors",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsored_donations",
                to="register.sponsor",
            ),
        ),
    ]
