# Generated by Django 3.2.7 on 2023-10-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0001_initial'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='athlete',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='register.athlete'),
        ),
        migrations.AddField(
            model_name='donation',
            name='sponsors',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_donations', to='register.sponsor'),
        ),
    ]
