# Generated by Django 3.2.7 on 2023-10-04 09:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_sponsor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, region=None),
        ),
    ]
