# Generated by Django 3.2.6 on 2023-09-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Sponsor_ID', models.CharField(max_length=20)),
                ('Organisation', models.CharField(max_length=255)),
                ('Bio', models.TextField()),
                ('sponsorship_start_date', models.DateField()),
                ('sponsorship_end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Sponsor',
            },
        ),
    ]
