# Generated by Django 3.2.6 on 2023-09-08 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='Sponsor_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
