# Generated by Django 3.2.6 on 2023-09-08 09:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_alter_sponsor_sponsor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
