# Generated by Django 3.2.6 on 2023-09-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_auto_20230908_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='Organisation',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='Sponsor_ID',
            new_name='sponsor_ID',
        ),
    ]
