# Generated by Django 3.2.6 on 2023-09-09 16:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0004_auto_20230909_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name_plural': 'Sponsors'},
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='id',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
