# Generated by Django 3.2.6 on 2023-09-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0005_auto_20230909_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='sponsor_ID',
            new_name='sponsor_id',
        ),
    ]
