# Generated by Django 3.2.6 on 2023-09-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0006_rename_sponsor_id_sponsor_sponsor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='phoneNumber',
            field=models.CharField(max_length=20),
        ),
    ]
