# Generated by Django 3.2.6 on 2023-09-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0007_alter_sponsor_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='sponsor_id',
            new_name='sponsor_ID',
        ),
    ]
