# Generated by Django 3.2.6 on 2023-09-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0008_rename_sponsor_id_sponsor_sponsor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='sponsor_ID',
            new_name='sponsor_id',
        ),
    ]
