# Generated by Django 3.2.6 on 2023-09-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0009_rename_sponsor_id_sponsor_sponsor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
