# Generated by Django 3.2.6 on 2023-09-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0010_alter_sponsor_sponsor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
