# Generated by Django 3.2.6 on 2023-09-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0011_auto_20230910_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_id',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
