# Generated by Django 3.2.6 on 2023-09-10 12:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0015_auto_20230910_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
