# Generated by Django 3.2.6 on 2023-09-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0025_auto_20230910_1217'),
    ]

    operations = [
    ]
