# Generated by Django 3.2.6 on 2023-09-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0030_auto_20230910_1218'),
    ]

    operations = [
    ]
