# Generated by Django 3.2.6 on 2023-09-10 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0031_auto_20230910_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_id',
            # field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
            field = models.CharField(max_length=10, unique=True, null=False, blank=False, default=None)
        ),
    ]
