# Generated by Django 4.2.5 on 2023-09-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='profile_picture',
        ),
    ]
