# Generated by Django 4.2.5 on 2023-09-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsor",
            name="Sponsor_ID",
        ),
    ]
