# Generated by Django 4.2.5 on 2023-09-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="sponsorship_end_date",
        ),
    ]
